### ISSUE TITLE
Serious Bug in Starting a new Run for a Competition

### ISSUE THREAD

**Issue by klschoef** [lucaro/DRES#174] opened 2020-10-05 15:21 UTC
When starting a new run for a competition (e.g., "LSC2020 Test" as name" and "SYNCHRONOUS" as type) the server responds with a toast message "Error: Index 7367 out of bounds for length 2"

**Comment by lucaro** [comment] 2020-10-05 15:52
Could you please provide additional detail, such as backend logs and the database contents, in order to allow for reproduction of the issue?

**Comment by ppanopticon** [comment] 2020-10-06 07:53
The bug seems to be related to a corrupted _runs.db_ file. Removing runs.db should fix the problem.

As to what caused the corruption; we're not quite sure (yet). However, we added a rollback() mechanism to the DAOs involved in case something goes wrong during serialisation.

**Comment by lucaro** [comment] 2020-10-07 18:11
Since we could not reproduce this and hence stabilized the database logic, I'll close this for now.

**Closed by lucaro** 2020-10-07 18:11 UTC
Labels: breaking, bug, urgent
